#########################【本地库】#############################
jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://124.239.152.85:63326/sgfx2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#jdbc.username=root
#jdbc.password=jlqA0jKG3PJ4q!JD
jdbc.url=jdbc:mysql://localhost:3306/fljcxt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
jdbc.username=root
jdbc.password=6909
jdbc.maxActive=60

#datasource base
datasource.defaultAutoCommit=true
datasource.initialSize=2
datasource.minIdle=1
datasource.maxWait=5000
datasource.testWhileIdle=true
datasource.testOnBorrow=true
datasource.testOnReturn=false
datasource.validationQuery=SELECT 1 FROM DUAL
datasource.timeBetweenEvictionRunsMillis=30000
datasource.minEvictableIdleTimeMillis=60000
datasource.maxEvictableIdleTimeMillis=900000
datasource.logAbandoned=true
datasource.removeAbandoned=true
datasource.removeAbandonedTimeout=120
datasource.filters=stat
datasource.asyncInit=true


