#redis settings
redis.keyPrefix=dtsite
redis.host=localhost
redis.port=6379

#============================#
#==== Framework settings ====#
#============================#

#\u7f13\u5b58\u8bbe\u7f6e
ehcache.configFile=config/cache/ehcache-local.xml
#ehcache.configFile=config/cache/ehcache-rmi.xml


